import { describe, expect, it } from "vitest";
import { formatJsonReport } from "../src/reporters/jsonReporter.js";
import { formatMarkdownReport } from "../src/reporters/markdownReporter.js";
import type { ScanResult } from "../src/scanner/types.js";

describe("formatMarkdownReport", () => {
  it("includes all required report sections", () => {
    const report = formatMarkdownReport(makeResult());

    expect(report).toContain("# Repo Doctor AI Report");
    expect(report).toContain("## Repository");
    expect(report).toContain("| Repository | `example` |");
    expect(report).toContain("| Generated | `2026-01-01T00:00:00.000Z` |");
    expect(report).toContain("| Overall score | **50/100** |");
    expect(report).toContain("## Category Scores");
    expect(report).toContain("| Presentation | 50/100 |");
    expect(report).toContain("## Detected Stacks");
    expect(report).toContain("**node** (primary)");
    expect(report).toContain("scripts: test, build");
    expect(report).toContain("## Summary");
    expect(report).toContain("| 0 | 1 | 1 | 0 |");
    expect(report).toContain("## Top Fixes");
    expect(report).toContain("Add SECURITY.md.");
    expect(report).toContain("## Full Check Table");
    expect(report).toContain("| Security policy | Security Hygiene | FAIL | high | Missing SECURITY.md. | Add SECURITY.md. |");
    expect(report).toContain("## Recommended Next Steps");
    expect(report).toContain("Generated by [Repo Doctor AI](https://www.npmjs.com/package/repo-doctor-ai).");
  });

  it("escapes table pipes in check content", () => {
    const result = makeResult();
    result.checks[0] = {
      ...result.checks[0],
      message: "Missing SECURITY.md | policy.",
      recommendation: "Add SECURITY.md | contact."
    };

    const report = formatMarkdownReport(result);

    expect(report).toContain("Missing SECURITY.md \\| policy.");
    expect(report).toContain("Add SECURITY.md \\| contact.");
  });
});

describe("formatJsonReport", () => {
  it("serializes the full ScanResult", () => {
    const result = makeResult();
    const parsed = JSON.parse(formatJsonReport(result));

    expect(parsed).toEqual(result);
  });
});

function makeResult(): ScanResult {
  return {
      repoPath: "/tmp/example",
      repoName: "example",
      generatedAt: "2026-01-01T00:00:00.000Z",
      detectedStacks: [
        {
          name: "node",
          confidence: "high",
          indicators: ["package.json"],
          scripts: ["test", "build"]
        }
      ],
      primaryStack: "node",
      score: {
        overall: 50,
        categories: {
          presentation: 50,
          buildTest: 50,
          cicd: 50,
          security: 50,
          contributors: 50
        }
      },
      checks: [
        {
          id: "security.policy",
          title: "Security policy",
          category: "security",
          status: "fail",
          severity: "high",
          message: "Missing SECURITY.md.",
          recommendation: "Add SECURITY.md."
        },
        {
          id: "security.codeql",
          title: "CodeQL workflow",
          category: "security",
          status: "warn",
          severity: "low",
          message: "No CodeQL workflow detected.",
          recommendation: "Consider adding CodeQL."
        }
      ],
      summary: { passed: 0, warnings: 1, failed: 1, critical: 0 },
      topFixes: [
        {
          id: "security.policy",
          title: "Security policy",
          category: "security",
          status: "fail",
          severity: "high",
          message: "Missing SECURITY.md.",
          recommendation: "Add SECURITY.md."
        }
      ]
    };
}
