import type { Category, CheckResult, ScanResult } from "../scanner/types.js";

const categoryLabels: Record<Category, string> = {
  presentation: "Presentation",
  buildTest: "Build/Test Readiness",
  cicd: "CI/CD Health",
  security: "Security Hygiene",
  contributors: "Contributor Readiness"
};

const categoryOrder: Category[] = ["presentation", "buildTest", "cicd", "security", "contributors"];

export function formatMarkdownReport(result: ScanResult): string {
  const stackList =
    result.detectedStacks.length > 0
      ? result.detectedStacks
          .map((stack) => {
            const primary = stack.name === result.primaryStack ? " (primary)" : "";
            const indicators = stack.indicators.length > 0 ? ` - ${stack.indicators.join(", ")}` : "";
            const scripts =
              stack.scripts && stack.scripts.length > 0 ? ` - scripts: ${stack.scripts.join(", ")}` : "";
            return `- **${escapeMarkdown(stack.name)}**${primary} (${stack.confidence} confidence)${indicators}${scripts}`;
          })
          .join("\n")
      : "- No stack detected";

  const topFixes = result.topFixes
    .slice(0, 5)
    .map(
      (check, index) =>
        `${index + 1}. **${statusLabel(check)}** ${escapeMarkdown(check.recommendation)}`
    )
    .join("\n");

  const categoryRows = categoryOrder
    .map((category) => `| ${categoryLabels[category]} | ${result.score.categories[category]}/100 |`)
    .join("\n");

  const checks = result.checks.map(formatCheckRow).join("\n");

  return `# Repo Doctor AI Report

## Repository

| Field | Value |
| --- | --- |
| Repository | \`${escapeMarkdown(result.repoName)}\` |
| Generated | \`${result.generatedAt}\` |
| Overall score | **${result.score.overall}/100** |

## Category Scores

| Category | Score |
| --- | ---: |
${categoryRows}

## Detected Stacks

${stackList}

## Summary

| Passed | Warnings | Failed | Critical |
| ---: | ---: | ---: | ---: |
| ${result.summary.passed} | ${result.summary.warnings} | ${result.summary.failed} | ${result.summary.critical} |

## Top Fixes

${topFixes || "No fixes available yet."}

## Full Check Table

| Check | Category | Status | Severity | Message | Recommendation |
| --- | --- | --- | --- | --- | --- |
${checks}

## Recommended Next Steps

${formatRecommendedNextSteps(result.topFixes)}

---

Generated by [Repo Doctor AI](https://www.npmjs.com/package/repo-doctor-ai).
`;
}

function formatCheckRow(check: CheckResult): string {
  return [
    escapeTableCell(check.title),
    categoryLabels[check.category],
    statusLabel(check),
    check.severity,
    escapeTableCell(check.message),
    escapeTableCell(check.recommendation)
  ].join(" | ").replace(/^/, "| ").replace(/$/, " |");
}

function formatRecommendedNextSteps(topFixes: CheckResult[]): string {
  if (topFixes.length === 0) {
    return "1. Keep the repository checks green as the project evolves.";
  }

  return topFixes
    .slice(0, 3)
    .map((check, index) => `${index + 1}. ${escapeMarkdown(check.recommendation)}`)
    .join("\n");
}

function statusLabel(check: CheckResult): string {
  if (check.status === "pass") return "PASS";
  if (check.status === "warn") return "WARN";
  return "FAIL";
}

function escapeTableCell(value: string): string {
  return escapeMarkdown(value).replace(/\n/g, " ").replace(/\|/g, "\\|");
}

function escapeMarkdown(value: string): string {
  return value.replace(/`/g, "\\`");
}
